cache:
  paths:
    - venv

stages:
  - test
  - build

test:
  stage: test
  script: ./do test --filter="*np_util_statemachine_t_core*"
  artifacts:
    reports:
      junit: report.xml

build:linux:
  stage: build
  script: ./do build

build:freebsd:
  stage: build
  script: ./do build