cache:
  paths:
    - venv

stages:
  - test
  - build
  - package
  - smoke_tests
  - release

test:
  stage: test
  script: ./do test --filter="*np_util_statemachine_t_core*"
  artifacts:
    reports:
      junit: report.xml

build:linux:
  stage: build
  script: ./do build linux
  artifacts:
    name: neuropil-linux
    paths:
      - build/linux
    
build:freebsd:
  stage: build
  script: ./do build freebsd
  artifacts:
    name: neuropil-freebsd
    paths:
      - build/freebsd

build:documentation:
  stage: build
  script: ./do doc
  artifacts:
    name: neuropil-documentation
    paths:
      - build/doc/html

package:
  stage: package
  script: ./do package
  artifacts:
    name: neuropil-release
    paths:
      - build/linux/*.tar.gz*
      - build/freebsd/*.tar.gz*
  dependencies:
    - build:documentation
    - build:freebsd
    - build:linux

smoke_tests:
  stage: smoke_tests
  script: true || to define
  dependencies:
    - package

PRD:tag:
  stage: release
  script: ./do release
  when: manual
  dependencies:
    - package

PRD:files:
  stage: release
  script: false || to define
  when: manual
  dependencies:
    - package

PRD:documentation:
  stage: release
  script: false || to define
  when: manual
  dependencies:
    - build:documentation

PRD:demo:
  stage: release
  script: 
    - ssh -o StrictHostKeyChecking=no demo_deploy /usr/local/bin/supervisorctl stop all
    - ssh -o StrictHostKeyChecking=no demo_deploy rm neuropil/*neuropil*
    - scp -r bin/. demo_deploy:/home/neuropil_deploy/neuropil
    - scp -r build/lib/. demo_deploy:/home/neuropil_deploy/neuropil
    - ssh -o StrictHostKeyChecking=no demo_deploy /usr/local/bin/supervisorctl start all
  when: manual
  dependencies:
    - build:documentation    

TST:files:
  stage: release
  script: false || to define
  dependencies:
    - package

TST:documentation:
  stage: release
  script: false || to define
  dependencies:
    - build:documentation
