stages:
  - test
  - build

before_script:
  - ls -lh
  
test:
  stage: test
  script: ./do test --filter="*np_util_statemachine_t_core*"
  artifacts:
    reports:
      junit: report.xml
  cache:
    paths:
      - venv

build:linux:
  stage: build
  script: ./do build

build:freebsd:
  stage: build
  script: ./do build