cache:
  paths:
    - venv

stages:
  - test
  - build
  - release

test:
  stage: test
  script: ./do test --filter="*np_util_statemachine_t_core*"
  artifacts:
    reports:
      junit: report.xml

build:linux:
  stage: build
  script: ./do build linux
  artifacts:
    name: neuropil-linux
    paths:
      - build/linux
    
build:freebsd:
  stage: build
  script: ./do build freebsd
  artifacts:
    name: neuropil-freebsd
    paths:
      - build/freebsd

build:documentation:
  stage: build
  script: ./do doc
  artifacts:
    name: neuropil-documentation
    paths:
      - build/doc/html



release:
  stage: release
  script: ./do release
  dependencies:
    - build:documentation
    - build:freebsd
    - build:linux

