cache:
  key: "${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}"
  paths:
    - venv

stages:
  - test
  - build
  - qa
  - release

test:
  stage: test
  script: ./do test
  artifacts:
    reports:
      junit: neuropil_test_suite-junit.xml
  except:
      - neuropil_.*
      - latest_release

build:linux:
  stage: build
  script: ./do build linux
  artifacts:
    name: neuropil-linux
    paths:
      - build/linux
  except:
      - neuropil_.*
      - latest_release
    
#build:freebsd:
#  stage: build
#  script: ./do build freebsd
#  artifacts:
#    name: neuropil-freebsd
#    paths:
#      - build/freebsd

build:documentation:
  stage: build
  script: ./do doc
  artifacts:
    name: neuropil-documentation
    paths:
      - build/doc/html
  except:
      - neuropil_.*
      - latest_release

qa:smoke_tests:
  stage: qa
  script: 
      - ./do smoke
  artifacts:
    reports:
      junit: smoke_test-junit.xml

qa:package:
  stage: qa
  script: 
    - ./do package
  artifacts:
    name: neuropil-release
    paths:
      - build/package/*
  only:
    - master
  except:
      - neuropil_.*
      - latest_release
  dependencies:
    - build:documentation

release:
  stage: release
  script: 
    - ./do release
    # auto saltstack deploy
  when: manual
  only:
    - master
  except:
      - neuropil_.*
      - latest_release
  dependencies:
    - qa:package
    - build:documentation
