default:
  image: $CI_REGISTRY_IMAGE/dev-enviroment

cache:
  key: "${CI_COMMIT_SHA}"
  paths:
    - .venv
    - build

stages:
  - enviroment
  - test
  - build
  - package
  - qa
  - release

setup:
  stage: enviroment
  before_script:
    - docker info
  script:
    - sh -c '[ -z "$CI_DEPLOY_USER" ] &&  (echo "Please read CI.md for the gitlab pipeline setup." >&2) && exit 1 || exit 0'
    - echo "$CI_DEPLOY_PASSWORD" | docker login -u $CI_DEPLOY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/dev-enviroment:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/dev-enviroment -f configs/docker/dev-enviroment.Dockerfile --build-arg CI_REPOSITORY_URL=$CI_REPOSITORY_URL --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA --build-arg GITLAB_USER_EMAIL=$GITLAB_USER_EMAIL configs/docker/
    - docker push $CI_REGISTRY_IMAGE/dev-enviroment
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - configs/docker/*
        - requirements.txt
        - SConstruct

test:
  stage: test
  script: ./do test
  retry:
    max: 2
  artifacts:
    reports:
      junit: build/neuropil_test_suite-junit.xml
    paths:
      - build/logs/*
      - build/core.*
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG == null'

build:documentation:
  stage: build
  script: ./do doc
  artifacts:
    name: neuropil-documentation
    paths:
      - build/doc/html

build:linux:
  stage: build
  script:
    - ./do build release
    - ./do build release bindings=1
  artifacts:
    name: neuropil-linux
    paths:
      - build/neuropil

package:linux:
  stage: package
  script:
    - ls build
    - ls build/neuropil
    - ./do package
    - mkdir -p neuropil
    - mv build/package/* neuropil/
  artifacts:
    name: neuropil-linux
    paths:
      - neuropil
    expire_in: 2 year
  rules:
    - if: '$CI_COMMIT_TAG != null && $CI_COMMIT_REF_PROTECTED'
  dependencies:
    - build:linux
    - build:documentation

qa:smoke_tests:
  stage: qa
  script:
      - ./do smoke --fail-fast
  retry:
    max: 2
  allow_failure: true
  timeout: 10m
  artifacts:
    reports:
      junit: build/smoke_test-junit.xml
    paths:
      - build/logs/*
      - build/core.*
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG == null'

request:
  stage: release
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: '$CI_COMMIT_REF_PROTECTED'
  trigger:
    include: .gitlab-ci-deployment.yml