cache:
  paths:
    - venv

stages:
  - test
  - build
  - prepare
  - smoke_tests
  - release

test:
  stage: test
  script: ./do test --filter="*np_util_statemachine_t_core*"
  artifacts:
    reports:
      junit: report.xml

build:linux:
  stage: build
  script: ./do build linux
  artifacts:
    name: neuropil-linux
    paths:
      - build/linux
    
build:freebsd:
  stage: build
  script: ./do build freebsd
  artifacts:
    name: neuropil-freebsd
    paths:
      - build/freebsd

build:documentation:
  stage: build
  script: ./do doc
  artifacts:
    name: neuropil-documentation
    paths:
      - build/doc/html

prepare:
  stage: prepare
  script: ./do collect --pw "$NEUROPIL_BUILD_PW" --sign_file "$NEUROPIL_BUILD_KEYFILE"
  artifacts:
    name: neuropil-release
    paths:
      - build/linux/*.tar.gz*
      - build/freebsd/*.tar.gz*
  dependencies:
    - build:documentation
    - build:freebsd
    - build:linux

smoke_tests:
  stage: smoke_tests
  script: true || to define
  dependencies:
    - prepare

PRD:files:
  stage: release
  script: false || to define
  when: manual
  dependencies:
    - prepare

PRD:documentation:
  stage: release
  script: false || to define
  when: manual
  dependencies:
    - build:documentation

TST:files:
  stage: release
  script: false || to define
  dependencies:
    - prepare

TST:documentation:
  stage: release
  script: false || to define
  dependencies:
    - build:documentation
