cache:
  paths:
    - venv

stages:
  - test
  - build
  - package
  - qa
  - release

test:
  stage: test
  script: ./do test
  artifacts:
    reports:
      junit: report.xml

build:linux:
  stage: build
  script: ./do build linux
  artifacts:
    name: neuropil-linux
    paths:
      - build/linux
    
#build:freebsd:
#  stage: build
#  script: ./do build freebsd
#  artifacts:
#    name: neuropil-freebsd
#    paths:
#      - build/freebsd

build:documentation:
  stage: build
  script: ./do doc
  artifacts:
    name: neuropil-documentation
    paths:
      - build/doc/html

package:
  stage: package
  script: ./do package
  artifacts:
    name: neuropil-release
    paths:
      - build/package/*
  dependencies:
    - build:documentation
    #- build:freebsd
    - build:linux

qa:deployment:
  stage: qa
  script: 
      - ./do deploy test
      # auto saltstack deploy
  dependencies:
    - package

qa:smoke_test:
  stage: qa
  script: 
      - ./do smoke
  dependencies:
    - qa:deployment

qa:approval:
  stage: qa
  script: 
      - ./do deploy production
  when: manual
  dependencies:
    - qa:smoke_test

release:
  stage: release
  before_script: 
    - ./do prepare_ci
  script: 
    - ./do release
    # auto saltstack deploy
  dependencies:
    - package
    - build:documentation   
    - qa:approval 
